## Medicare EDA Part D data 2017

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import time
import pprint

%matplotlib inline

In [3]:
part_d_data = pd.read_csv("../data/Medicare_Provider_Utilization_and_Payment_Data__Part_D_Prescriber_Summary_Table_CY2017.csv")
part_d_data.head()

,npi,nppes_provider_last_org_name,nppes_provider_first_name,nppes_provider_mi,nppes_credentials,nppes_provider_gender,nppes_entity_code,nppes_provider_street1,nppes_provider_street2,nppes_provider_city,...,beneficiary_male_count,beneficiary_race_white_count,beneficiary_race_black_count,beneficiary_race_asian_pi_count,beneficiary_race_hispanic_count,beneficiary_race_nat_ind_count,beneficiary_race_other_count,beneficiary_nondual_count,beneficiary_dual_count,beneficiary_average_risk_score
0,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,92.0,220.0,14.0,0.0,0.0,0.0,0.0,143.0,91.0,2.1685
1,1003000142,KHALIL,RASHID,NaN,M.D.,M,I,4126 N HOLLAND SYLVANIA RD,SUITE 220,TOLEDO,...,92.0,195.0,58.0,NaN,NaN,0.0,NaN,143.0,133.0,1.8029
2,1003000167,ESCOBAR,JULIO,E,DDS,M,I,5 PINE CONE RD,NaN,DAYTON,...,17.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,1.0598
3,1003000175,REYES-VASQUEZ,BELINDA,NaN,D.D.S.,F,I,322 N AZUSA AVE STE 202,NaN,LA PUENTE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1003000282,BLAKEMORE,ROSIE,K,FNP,F,I,TENNESSEE PRISON FOR WOMEN,3881 STEWARTS LANE,NASHVILLE,...,NaN,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,4.5148

In [4]:
list(part_d_data.columns)

['npi',
 'nppes_provider_last_org_name',
 'nppes_provider_first_name',
 'nppes_provider_mi',
 'nppes_credentials',
 'nppes_provider_gender',
 'nppes_entity_code',
 'nppes_provider_street1',
 'nppes_provider_street2',
 'nppes_provider_city',
 'nppes_provider_zip5',
 'nppes_provider_zip4',
 'nppes_provider_state',
 'nppes_provider_country',
 'specialty_description',
 'description_flag',
 'medicare_prvdr_enroll_status',
 'total_claim_count',
 'total_30_day_fill_count',
 'total_drug_cost',
 'total_day_supply',
 'bene_count',
 'ge65_suppress_flag',
 'total_claim_count_ge65',
 'total_30_day_fill_count_ge65',
 'total_drug_cost_ge65',
 'total_day_supply_ge65',
 'bene_count_ge65_suppress_flag',
 'bene_count_ge65',
 'brand_suppress_flag',
 'brand_claim_count',
 'brand_drug_cost',
 'generic_suppress_flag',
 'generic_claim_count',
 'generic_drug_cost',
 'other_suppress_flag',
 'other_claim_count',
 'other_drug_cost',
 'mapd_suppress_flag',
 'mapd_claim_count',
 'mapd_drug_cost',
 'pdp_suppress_flag',
 'pdp_claim_count',
 'pdp_drug_cost',
 'lis_suppress_flag',
 'lis_claim_count',
 'lis_drug_cost',
 'nonlis_suppress_flag',
 'nonlis_claim_count',
 'nonlis_drug_cost',
 'opioid_claim_count',
 'opioid_drug_cost',
 'opioid_day_supply',
 'opioid_bene_count',
 'opioid_prescriber_rate',
 'la_opioid_claim_count',
 'la_opioid_drug_cost',
 'la_opioid_day_supply',
 'la_opioid_bene_count',
 'la_opioid_prescriber_rate',
 'antibiotic_claim_count',
 'antibiotic_drug_cost',
 'antibiotic_bene_count',
 'antipsych_ge65_suppress_flag',
 'antipsych_claim_count_ge65',
 'antipsych_drug_cost_ge65',
 'antipsych_bene_ge65_suppress_flg',
 'antipsych_bene_count_ge65',
 'average_age_of_beneficiaries',
 'beneficiary_age_less_65_count',
 'beneficiary_age_65_74_count',
 'beneficiary_age_75_84_count',
 'beneficiary_age_greater_84_count',
 'beneficiary_female_count',
 'beneficiary_male_count',
 'beneficiary_race_white_count',
 'beneficiary_race_black_count',
 'beneficiary_race_asian_pi_count',
 'beneficiary_race_hispanic_count',
 'beneficiary_race_nat_ind_count',
 'beneficiary_race_other_count',
 'beneficiary_nondual_count',
 'beneficiary_dual_count',
 'beneficiary_average_risk_score']

In [7]:
part_d_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1162898 entries, 0 to 1162897
Data columns (total 84 columns):
 #   Column                            Non-Null Count    Dtype
---  ------                            --------------    -----
 0   npi                               1162898 non-null  int64
 1   nppes_provider_last_org_name      1162864 non-null  object
 2   nppes_provider_first_name         1162876 non-null  object
 3   nppes_provider_mi                 801371 non-null   object
 4   nppes_credentials                 1092160 non-null  object
 5   nppes_provider_gender             1162895 non-null  object
 6   nppes_entity_code                 1162898 non-null  object
 7   nppes_provider_street1            1162897 non-null  object
 8   nppes_provider_street2            428496 non-null   object
 9   nppes_provider_city               1162898 non-null  object
 10  nppes_provider_zip5               1162846 non-null  float64
 11  nppes_provider_zip4               1005831 non-null  float64
 12  nppes_provider_state              1162898 non-null  object
 13  nppes_provider_country            1162898 non-null  object
 14  specialty_description             1162898 non-null  object
 15  description_flag                  1162898 non-null  object
 16  medicare_prvdr_enroll_status      1162898 non-null  object
 17  total_claim_count                 1162898 non-null  int64
 18  total_30_day_fill_count           1162898 non-null  float64
 19  total_drug_cost                   1162898 non-null  float64
 20  total_day_supply                  1162898 non-null  int64
 21  bene_count                        1031058 non-null  float64
 22  ge65_suppress_flag                252456 non-null   object
 23  total_claim_count_ge65            910442 non-null   float64
 24  total_30_day_fill_count_ge65      910442 non-null   float64
 25  total_drug_cost_ge65              910442 non-null   float64
 26  total_day_supply_ge65             910442 non-null   float64
 27  bene_count_ge65_suppress_flag     517592 non-null   object
 28  bene_count_ge65                   645306 non-null   float64
 29  brand_suppress_flag               470339 non-null   object
 30  brand_claim_count                 692559 non-null   float64
 31  brand_drug_cost                   692559 non-null   float64
 32  generic_suppress_flag             316337 non-null   object
 33  generic_claim_count               846561 non-null   float64
 34  generic_drug_cost                 846561 non-null   float64
 35  other_suppress_flag               247970 non-null   object
 36  other_claim_count                 914928 non-null   float64
 37  other_drug_cost                   914928 non-null   float64
 38  mapd_suppress_flag                226732 non-null   object
 39  mapd_claim_count                  936166 non-null   float64
 40  mapd_drug_cost                    936166 non-null   float64
 41  pdp_suppress_flag                 226732 non-null   object
 42  pdp_claim_count                   936166 non-null   float64
 43  pdp_drug_cost                     936166 non-null   float64
 44  lis_suppress_flag                 240873 non-null   object
 45  lis_claim_count                   922025 non-null   float64
 46  lis_drug_cost                     922025 non-null   float64
 47  nonlis_suppress_flag              240873 non-null   object
 48  nonlis_claim_count                922025 non-null   float64
 49  nonlis_drug_cost                  922025 non-null   float64
 50  opioid_claim_count                834341 non-null   float64
 51  opioid_drug_cost                  834341 non-null   float64
 52  opioid_day_supply                 834341 non-null   float64
 53  opioid_bene_count                 775464 non-null   float64
 54  opioid_prescriber_rate            834341 non-null   float64
 55  la_opioid_claim_count             1017426 non-null  float64
 56  la_opioid_drug_cost               1017426 non-null  float64
 57  la_opioid_day_supply              1017426 non-null  float64
 58  la_opioid_bene_count              947351 non-null   float64
 59  la_opioid_prescriber_rate         674916 non-null   float64
 60  antibiotic_claim_count            820872 non-null   float64
 61  antibiotic_drug_cost              820872 non-null   float64
 62  antibiotic_bene_count             762301 non-null   float64
 63  antipsych_ge65_suppress_flag      161125 non-null   object
 64  antipsych_claim_count_ge65        1001773 non-null  float64
 65  antipsych_drug_cost_ge65          1001773 non-null  float64
 66  antipsych_bene_ge65_suppress_flg  251659 non-null   object
 67  antipsych_bene_count_ge65         911239 non-null   float64
 68  average_age_of_beneficiaries      1031058 non-null  float64
 69  beneficiary_age_less_65_count     645306 non-null   float64
 70  beneficiary_age_65_74_count       540107 non-null   float64
 71  beneficiary_age_75_84_count       361504 non-null   float64
 72  beneficiary_age_greater_84_count  382527 non-null   float64
 73  beneficiary_female_count          822278 non-null   float64
 74  beneficiary_male_count            822278 non-null   float64
 75  beneficiary_race_white_count      557541 non-null   float64
 76  beneficiary_race_black_count      393942 non-null   float64
 77  beneficiary_race_asian_pi_count   510439 non-null   float64
 78  beneficiary_race_hispanic_count   404100 non-null   float64
 79  beneficiary_race_nat_ind_count    841993 non-null   float64
 80  beneficiary_race_other_count      346341 non-null   float64
 81  beneficiary_nondual_count         683625 non-null   float64
 82  beneficiary_dual_count            683625 non-null   float64
 83  beneficiary_average_risk_score    1031058 non-null  float64
dtypes: float64(56), int64(3), object(25)
memory usage: 745.3+ MB

In [14]:
part_d_data.beneficiary_average_risk_score.describe()

count    1.031058e+06
mean     1.527580e+00
std      7.118753e-01
min      3.110000e-01
25%      1.093700e+00
50%      1.346500e+00
75%      1.745200e+00
max      1.116440e+01
Name: beneficiary_average_risk_score, dtype: float64

In [5]:
part_d_data.beneficiary_average_risk_score.value_counts()

1.0665    141
1.2003    140
1.1430    138
1.0644    137
1.0791    137
         ...
3.9900      1
3.6926      1
3.9945      1
8.2138      1
3.6846      1
Name: beneficiary_average_risk_score, Length: 43205, dtype: int64

In [6]:
ge65_suppress = part_d_data.ge65_suppress_flag
ge65_suppress

0          NaN
1          NaN
2            #
3            #
4          NaN
          ...
1162893    NaN
1162894    NaN
1162895      #
1162896    NaN
1162897    NaN
Name: ge65_suppress_flag, Length: 1162898, dtype: object

In [11]:
part_d_data[part_d_data['nppes_entity_code'] == '0']
# all entity types are I- individual

Empty DataFrame
Columns: [npi, nppes_provider_last_org_name, nppes_provider_first_name, nppes_provider_mi, nppes_credentials, nppes_provider_gender, nppes_entity_code, nppes_provider_street1, nppes_provider_street2, nppes_provider_city, nppes_provider_zip5, nppes_provider_zip4, nppes_provider_state, nppes_provider_country, specialty_description, description_flag, medicare_prvdr_enroll_status, total_claim_count, total_30_day_fill_count, total_drug_cost, total_day_supply, bene_count, ge65_suppress_flag, total_claim_count_ge65, total_30_day_fill_count_ge65, total_drug_cost_ge65, total_day_supply_ge65, bene_count_ge65_suppress_flag, bene_count_ge65, brand_suppress_flag, brand_claim_count, brand_drug_cost, generic_suppress_flag, generic_claim_count, generic_drug_cost, other_suppress_flag, other_claim_count, other_drug_cost, mapd_suppress_flag, mapd_claim_count, mapd_drug_cost, pdp_suppress_flag, pdp_claim_count, pdp_drug_cost, lis_suppress_flag, lis_claim_count, lis_drug_cost, nonlis_suppress_flag, nonlis_claim_count, nonlis_drug_cost, opioid_claim_count, opioid_drug_cost, opioid_day_supply, opioid_bene_count, opioid_prescriber_rate, la_opioid_claim_count, la_opioid_drug_cost, la_opioid_day_supply, la_opioid_bene_count, la_opioid_prescriber_rate, antibiotic_claim_count, antibiotic_drug_cost, antibiotic_bene_count, antipsych_ge65_suppress_flag, antipsych_claim_count_ge65, antipsych_drug_cost_ge65, antipsych_bene_ge65_suppress_flg, antipsych_bene_count_ge65, average_age_of_beneficiaries, beneficiary_age_less_65_count, beneficiary_age_65_74_count, beneficiary_age_75_84_count, beneficiary_age_greater_84_count, beneficiary_female_count, beneficiary_male_count, beneficiary_race_white_count, beneficiary_race_black_count, beneficiary_race_asian_pi_count, beneficiary_race_hispanic_count, beneficiary_race_nat_ind_count, beneficiary_race_other_count, beneficiary_nondual_count, beneficiary_dual_count, beneficiary_average_risk_score]
Index: []

[0 rows x 84 columns]